#image: maven:3-eclipse-temurin-17

variables:
  GIT_DEPTH: "0"

stages:
  - build-sonar

build-sonar:
  stage: build-sonar
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - ".sonar/cache"
  script:
    - cd $CI_PROJECT_DIR
    - $sonar_host = Get-Content $env:SONAR_HOST_URL
    - $sonar_token = Get-Content $env:SONAR_TOKEN
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=$sonar_host -Dsonar.projectKey=yy-framework_yy-framework-api -Dsonar.login=$sonar_token -Dsonar.java.binaries=target/classes

  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
