package com.yy.ppm.finance.webserver.service.htxx;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * WbServiceImplService service = new WbServiceImplService();
 * WbServiceI portType = service.getWbServiceImplPort();
 * portType.selectInvoice(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "WbServiceImplService", targetNamespace = "com.htxx.service", wsdlLocation = "http://css.sdaisino.com:6666/FPGLXT/CXF/WbService?wsdl")
public class WbServiceImplService extends Service {

	private final static URL WBSERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(WbServiceImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = WbServiceImplService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://css.sdaisino.com:6666/FPGLXT/CXF/WbService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://css.sdaisino.com:6666/FPGLXT/CXF/WbService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public WbServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WbServiceImplService() {
		super(WBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("com.htxx.service",
				"WbServiceImplService"));
	}

	/**
	 *
	 * @return returns WbServiceI
	 */
	@WebEndpoint(name = "WbServiceImplPort")
	public WbServiceI getWbServiceImplPort() {
		return super.getPort(
				new QName("com.htxx.service", "WbServiceImplPort"),
				WbServiceI.class);
	}

}
