package com.yy.ppm.finance.webserver.service.htxx;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "WbServiceI", targetNamespace = "com.htxx.service")
public interface WbServiceI {

	/**
	 *
	 * @param number
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://com.htxx.service/selectInvoice")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "selectInvoice", targetNamespace = "com.htxx.service", className = "service.htxx.com.SelectInvoice")
	@ResponseWrapper(localName = "selectInvoiceResponse", targetNamespace = "com.htxx.service", className = "service.htxx.com.SelectInvoiceResponse")
	public String selectInvoice(
			@WebParam(name = "number", targetNamespace = "") String number);

	/**
	 *
	 * @param data
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://com.htxx.service/sendData")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendData", targetNamespace = "com.htxx.service", className = "service.htxx.com.SendData")
	@ResponseWrapper(localName = "sendDataResponse", targetNamespace = "com.htxx.service", className = "service.htxx.com.SendDataResponse")
	public String sendData(
			@WebParam(name = "data", targetNamespace = "") String data);

}
